// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://widjgbkplnxakvjyfzis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpZGpnYmtwbG54YWt2anlmemlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjM0NzYsImV4cCI6MjA2MTkzOTQ3Nn0.P_D3VuL8TEQlL06UeylpAAMobZd_wDxW2pNowLZb8aw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);